<rule-set name="one admin rule"
          xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java"
          xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
          xs:schemaLocation="http://drools.org/rules rules.xsd
    				                   http://drools.org/semantics/java java.xsd">

  <java:import>java.lang.Object</java:import>
  <java:import>java.lang.String</java:import>
  <java:import>java.util.Map</java:import>
  <java:import>org.exoplatform.container.PortalContainer</java:import>
  <java:import>org.exoplatform.services.organization.OrganizationService</java:import>
  <java:import>org.exoplatform.commons.utils.PageList</java:import>  
  <java:import>org.exoplatform.services.cms.CmsService</java:import>  

  <java:functions>
    public int getNumberOfAdmins() throws Exception{
      PortalContainer pC = PortalContainer.getInstance();
      OrganizationService oS = (OrganizationService) pC.getComponentInstanceOfType(OrganizationService.class);
      return oS.findUsersByGroup("/admin").getAll().size();
    }
    
    public void processMove(Map variables) throws Exception {        
      String nodePath = (String) variables.get("nodePath"); 
      String srcWorkspace = (String) variables.get("srcWorkspace"); 
      String destWorkspace = (String) variables.get("destWorkspace"); 
      String destPath = (String) variables.get("destPath");  
      PortalContainer pC = PortalContainer.getInstance();
      CmsService cmsService = (CmsService) pC.getComponentInstanceOfType(CmsService.class);
      cmsService.moveNode(nodePath, srcWorkspace, destWorkspace, destPath);
    }
  </java:functions>

  <rule name="Admin exists">
    <parameter identifier="variables">
      <class>Map</class>
    </parameter>
    <java:condition>getNumberOfAdmins() == 1</java:condition>
    <java:consequence>
      System.out.println( "Enougth admins x == 1 : " + getNumberOfAdmins());
      processMove(variables);
    </java:consequence>
  </rule>

</rule-set>